### ISSUE TITLE
[Rule Submit] LAYOUT: Key columns should be hidden

### ISSUE THREAD

**Issue by Gezahegne** [TabularEditor/BestPracticeRules#14]
"ID": "LAYOUT:_KEY_COLUMNS_SHOULD_BE_HIDDEN
",
    "Name": "LAYOUT: Key columns should be hidden",
    "Category": null,
    "Description": "Key columns that are used as Primary and foreign keys should be hidden from clients.",
    "Severity": 3,
    "Scope": "DataColumn, CalculatedColumn, CalculatedTableColumn",
    "ScopeString": "Columns",
    "Expression": "(Name.ToLower().EndsWith(\"id\") or Name.ToLower().EndsWith(\"key\"))\nand not IsHidden",
    "FixExpression": null,
    "Compatibility": null,
    "IsValid": false

**Comment by otykier** [comment]
Agreed. Instead of relying on naming conventions, we can use the UsedInRelationships collection, to check if the column participates as the "FromColumn" of any relationship in the model, in which case, we can regard it as a FK that should be hidden:

```
UsedInRelationships.Any(FromColumn = outerIt) and not IsHidden and not Table.IsHidden
```

[Implemented here](https://github.com/TabularEditor/BestPracticeRules/blob/master/src/standard/Model%20Layout/LAYOUT_HIDE_FK_COLUMNS.json)
