### ISSUE TITLE
[Rule Submit] NAME: Attribute names should not have '_' '/' '\\'

### ISSUE THREAD

**Issue by Gezahegne** [TabularEditor/BestPracticeRules#17]
"ID": "NAME:_ATTRIBUTE_NAMES_SHOULDN'T_HAVE_'_'_'/'_'\\'",
    "Name": "NAME: Attribute names should not have '_' '/' '\\'",
    "Category": null,
    "Description": "Attribute names should not contain these special characters '_' '/' '\\' You may use camel case or spaces instead for readability.",
    "Severity": 3,
    "Scope": "DataColumn, CalculatedColumn, CalculatedTableColumn",
    "ScopeString": "Columns",
    "Expression": "(Name.Contains(\"_\") or Name.Contains(\"\\\") or Name.Contains(\"/\")) and not IsHidden",
    "FixExpression": null,
    "Compatibility": null,
    "IsValid": false

**Comment by otykier** [comment]
I'd like to start a discussion on the namings. I'm not sure if the standard set of rules for Tabular Editor should disallow the use of slashes in a column name. For example, it is common to have Flag-type columns named like [Yes/No]. Should this be discouraged?

Are we aware of any characters in column names that can cause problems in client tools? Because those should definitely be discouraged.

**Comment by otykier** [comment]
Won't add to standard repository, as this relies on organization-specific naming convention. If there are specific characters that are known to cause problems, please open a new issue.
