### ISSUE TITLE
Names of visible objects must separate names by space

### ISSUE THREAD

**Issue by marcosqlbi** [TabularEditor/BestPracticeRules#2]
Use names such as "Sales Amount" instead of "SalesAmount"

**Comment by otykier** [comment]
This rule will be split up into two. One for columns and hierarchies, and another for measures and tables. The reason is that the check for whether an object is visible is slightly different for these two groups of objects: Columns and hierarchies are always invisible if the parent table is hidden, where as (unhidden) measures are still visible even if the parent table is hidden.

For columns and hierarchies, we use the following expression:

```
not (IsHidden or Table.IsHidden) 
and RegEx.IsMatch(Name, "[A-Z]([A-Z0-9]*[a-z][a-z0-9]*[A-Z]|[a-z0-9]*[A-Z][A-Z0-9]*[a-z])[A-Za-z0-9]*") 
and not Name.Contains(" ") 
and (Model.Cultures.Count = 0 or TranslatedNames.Any(it = "" or it = outerIt.Name))
```

That is, catch all columns or hierarchies where:

- The object is not hidden, and the parent table is not hidden **AND**
- The name is in CamelCase using the RegEx from [this SO post](https://stackoverflow.com/a/1128326/1594867) **AND**
- The name does not contain any spaces, such as: [Product OverStocked] **AND**
- A translated name different from the object name has not been supplied (in case the model uses translations)

For measures and tables, the rule looks similar, but we skip the check on `Table.IsHidden`.

[Rule definition for columns and hierarchies](https://github.com/TabularEditor/BestPracticeRules/blob/master/src/standard/Naming/NO_CAMELCASE_COLUMNS_HIERARCHIES.json)
[Rule definition for measures and tables](https://github.com/TabularEditor/BestPracticeRules/blob/master/src/standard/Naming/NO_CAMELCASE_MEASURES_TABLES.json)
